version: "3.2"
services:
  app:
    container_name: sample-app
    build: .
    volumes: 
      - .:/app
    environment:
      LOG_LEVEL: debug
    ports:
      - "3000:3000"
    command: ["serve-develop"]
